# Generated by Django 3.0.3 on 2020-02-24 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_estate_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.CharField(blank=True, max_length=32)),
                ('workflow_name', models.TextField(blank=True)),
                ('job_status', models.CharField(choices=[('new', 'New'), ('init', 'Init'), ('requested', 'Requested'), ('retrive_error', 'Retrive_Error'), ('scheduled', 'Scheduled'), ('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('closed', 'Closed'), ('waiting', 'Waiting'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout'), ('canceled', 'Canceled'), ('canceling', 'Canceling'), ('paused', 'Paused'), ('pausing', 'Pausing'), ('resuming', 'Resuming')], default='init', max_length=32)),
                ('triger_at', models.DateTimeField(null=True)),
                ('requester', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_estate_api.Product')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
