# Generated by Django 3.0.3 on 2020-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_estate_api', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requester',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='workflow_name',
            field=models.TextField(),
        ),
    ]
