apiVersion: v1
kind: ServiceAccount
metadata:
  name:  resource-operator
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  - verbs: ["get", "list", "watch", "create", "delete", "replace", "patch"]
    resources: ["persistentvolumes", "pods", "services"]
    apiGroups: [""]
  - verbs: ["get", "list", "watch", "create", "delete", "replace", "patch"]
    resources: ["ingresses"]
    apiGroups: ["extensions"]
  - verbs: ["get", "list", "watch", "create", "delete", "replace", "patch"]
    resources: ["ingresses"]
    apiGroups: ["networking.k8s.io"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-binding
subjects:
  - kind: ServiceAccount
    name: resource-operator
    # replace with namespace where provisioner is deployed
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: operator-cluster-role
  apiGroup: rbac.authorization.k8s.io  

