# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='student',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservices.proto\x12\x07student\"\x0e\n\x0c\x45mptyRequest\"\x1e\n\x0eStudentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x0bStudentInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05phone\x18\x03 \x01(\t\"C\n\x0bStudentlist\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12%\n\x07members\x18\x02 \x03(\x0b\x32\x14.student.StudentInfo\"+\n\rStudentFilter\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\xa7\x02\n\x10StutdentsService\x12\x41\n\x0eGetStudentInfo\x12\x17.student.StudentRequest\x1a\x14.student.StudentInfo\"\x00\x12\x41\n\x0eGetStudentList\x12\x15.student.EmptyRequest\x1a\x14.student.StudentInfo\"\x00\x30\x01\x12\x43\n\x12GetStudentsByArray\x12\x15.student.EmptyRequest\x1a\x14.student.Studentlist\"\x00\x12H\n\x12GetSpecifyStudents\x12\x16.student.StudentFilter\x1a\x14.student.StudentInfo\"\x00(\x01\x30\x01\x62\x06proto3')
)




_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='student.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=41,
)


_STUDENTREQUEST = _descriptor.Descriptor(
  name='StudentRequest',
  full_name='student.StudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='student.StudentRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)


_STUDENTINFO = _descriptor.Descriptor(
  name='StudentInfo',
  full_name='student.StudentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='student.StudentInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='student.StudentInfo.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='student.StudentInfo.phone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=130,
)


_STUDENTLIST = _descriptor.Descriptor(
  name='Studentlist',
  full_name='student.Studentlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='student.Studentlist.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='members', full_name='student.Studentlist.members', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=199,
)


_STUDENTFILTER = _descriptor.Descriptor(
  name='StudentFilter',
  full_name='student.StudentFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='student.StudentFilter.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='student.StudentFilter.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=244,
)

_STUDENTLIST.fields_by_name['members'].message_type = _STUDENTINFO
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['StudentRequest'] = _STUDENTREQUEST
DESCRIPTOR.message_types_by_name['StudentInfo'] = _STUDENTINFO
DESCRIPTOR.message_types_by_name['Studentlist'] = _STUDENTLIST
DESCRIPTOR.message_types_by_name['StudentFilter'] = _STUDENTFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:student.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

StudentRequest = _reflection.GeneratedProtocolMessageType('StudentRequest', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:student.StudentRequest)
  ))
_sym_db.RegisterMessage(StudentRequest)

StudentInfo = _reflection.GeneratedProtocolMessageType('StudentInfo', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTINFO,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:student.StudentInfo)
  ))
_sym_db.RegisterMessage(StudentInfo)

Studentlist = _reflection.GeneratedProtocolMessageType('Studentlist', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTLIST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:student.Studentlist)
  ))
_sym_db.RegisterMessage(Studentlist)

StudentFilter = _reflection.GeneratedProtocolMessageType('StudentFilter', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTFILTER,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:student.StudentFilter)
  ))
_sym_db.RegisterMessage(StudentFilter)



_STUTDENTSSERVICE = _descriptor.ServiceDescriptor(
  name='StutdentsService',
  full_name='student.StutdentsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=247,
  serialized_end=542,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStudentInfo',
    full_name='student.StutdentsService.GetStudentInfo',
    index=0,
    containing_service=None,
    input_type=_STUDENTREQUEST,
    output_type=_STUDENTINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStudentList',
    full_name='student.StutdentsService.GetStudentList',
    index=1,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STUDENTINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStudentsByArray',
    full_name='student.StutdentsService.GetStudentsByArray',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STUDENTLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSpecifyStudents',
    full_name='student.StutdentsService.GetSpecifyStudents',
    index=3,
    containing_service=None,
    input_type=_STUDENTFILTER,
    output_type=_STUDENTINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUTDENTSSERVICE)

DESCRIPTOR.services_by_name['StutdentsService'] = _STUTDENTSSERVICE

# @@protoc_insertion_point(module_scope)
