// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: server/dataObj/vm.proto

package dataObj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Volume_Type int32

const (
	Volume_os   Volume_Type = 0
	Volume_data Volume_Type = 1
)

// Enum value maps for Volume_Type.
var (
	Volume_Type_name = map[int32]string{
		0: "os",
		1: "data",
	}
	Volume_Type_value = map[string]int32{
		"os":   0,
		"data": 1,
	}
)

func (x Volume_Type) Enum() *Volume_Type {
	p := new(Volume_Type)
	*p = x
	return p
}

func (x Volume_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Volume_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_server_dataObj_vm_proto_enumTypes[0].Descriptor()
}

func (Volume_Type) Type() protoreflect.EnumType {
	return &file_server_dataObj_vm_proto_enumTypes[0]
}

func (x Volume_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Volume_Type.Descriptor instead.
func (Volume_Type) EnumDescriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{0, 0}
}

type Volume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32       `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Name string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type Volume_Type `protobuf:"varint,3,opt,name=type,proto3,enum=VM.Volume_Type" json:"type,omitempty"`
}

func (x *Volume) Reset() {
	*x = Volume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_dataObj_vm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_server_dataObj_vm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{0}
}

func (x *Volume) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetType() Volume_Type {
	if x != nil {
		return x.Type
	}
	return Volume_os
}

type VM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    int32     `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory int32     `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks  []*Volume `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
}

func (x *VM) Reset() {
	*x = VM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_dataObj_vm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_server_dataObj_vm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{1}
}

func (x *VM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VM) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *VM) GetDisks() []*Volume {
	if x != nil {
		return x.Disks
	}
	return nil
}

type RequestString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *RequestString) Reset() {
	*x = RequestString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_dataObj_vm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestString) ProtoMessage() {}

func (x *RequestString) ProtoReflect() protoreflect.Message {
	mi := &file_server_dataObj_vm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestString.ProtoReflect.Descriptor instead.
func (*RequestString) Descriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{2}
}

func (x *RequestString) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ResponseString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ResponseString) Reset() {
	*x = ResponseString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_dataObj_vm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseString) ProtoMessage() {}

func (x *ResponseString) ProtoReflect() protoreflect.Message {
	mi := &file_server_dataObj_vm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseString.ProtoReflect.Descriptor instead.
func (*ResponseString) Descriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseString) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_dataObj_vm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_dataObj_vm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_dataObj_vm_proto_rawDescGZIP(), []int{4}
}

var File_server_dataObj_vm_proto protoreflect.FileDescriptor

var file_server_dataObj_vm_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a,
	0x2f, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x56, 0x4d, 0x22, 0x6f, 0x0a,
	0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x56, 0x4d, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x18, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x6f, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x10, 0x01, 0x22, 0x50,
	0x0a, 0x02, 0x56, 0x4d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x20,
	0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x56, 0x4d, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73,
	0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0x6f, 0x0a, 0x0e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d,
	0x12, 0x06, 0x2e, 0x56, 0x4d, 0x2e, 0x56, 0x4d, 0x1a, 0x12, 0x2e, 0x56, 0x4d, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x4d, 0x12, 0x11, 0x2e, 0x56, 0x4d, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x12, 0x2e,
	0x56, 0x4d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x22, 0x00, 0x32, 0x33, 0x0a, 0x07, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x28,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x09, 0x2e,
	0x56, 0x4d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x56, 0x4d, 0x2e, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_server_dataObj_vm_proto_rawDescOnce sync.Once
	file_server_dataObj_vm_proto_rawDescData = file_server_dataObj_vm_proto_rawDesc
)

func file_server_dataObj_vm_proto_rawDescGZIP() []byte {
	file_server_dataObj_vm_proto_rawDescOnce.Do(func() {
		file_server_dataObj_vm_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_dataObj_vm_proto_rawDescData)
	})
	return file_server_dataObj_vm_proto_rawDescData
}

var file_server_dataObj_vm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_dataObj_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_dataObj_vm_proto_goTypes = []interface{}{
	(Volume_Type)(0),       // 0: VM.Volume.Type
	(*Volume)(nil),         // 1: VM.Volume
	(*VM)(nil),             // 2: VM.VM
	(*RequestString)(nil),  // 3: VM.RequestString
	(*ResponseString)(nil), // 4: VM.ResponseString
	(*Empty)(nil),          // 5: VM.Empty
}
var file_server_dataObj_vm_proto_depIdxs = []int32{
	0, // 0: VM.Volume.type:type_name -> VM.Volume.Type
	1, // 1: VM.VM.disks:type_name -> VM.Volume
	2, // 2: VM.VirtualMachine.CreateVM:input_type -> VM.VM
	3, // 3: VM.VirtualMachine.DeleteVM:input_type -> VM.RequestString
	5, // 4: VM.Volumes.ListVolumes:input_type -> VM.Empty
	4, // 5: VM.VirtualMachine.CreateVM:output_type -> VM.ResponseString
	4, // 6: VM.VirtualMachine.DeleteVM:output_type -> VM.ResponseString
	1, // 7: VM.Volumes.ListVolumes:output_type -> VM.Volume
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_dataObj_vm_proto_init() }
func file_server_dataObj_vm_proto_init() {
	if File_server_dataObj_vm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_dataObj_vm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Volume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_dataObj_vm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_dataObj_vm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_dataObj_vm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_dataObj_vm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_dataObj_vm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_dataObj_vm_proto_goTypes,
		DependencyIndexes: file_server_dataObj_vm_proto_depIdxs,
		EnumInfos:         file_server_dataObj_vm_proto_enumTypes,
		MessageInfos:      file_server_dataObj_vm_proto_msgTypes,
	}.Build()
	File_server_dataObj_vm_proto = out.File
	file_server_dataObj_vm_proto_rawDesc = nil
	file_server_dataObj_vm_proto_goTypes = nil
	file_server_dataObj_vm_proto_depIdxs = nil
}
